export const fishingMapStyle = [
  { elementType: "geometry", stylers: [{ color: "#d7f3df" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#315f5d" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#effff7" }] },
  { featureType: "administrative", elementType: "geometry.stroke", stylers: [{ color: "#9bd7b0" }] },
  { featureType: "landscape.man_made", elementType: "geometry", stylers: [{ color: "#dff5df" }] },
  { featureType: "landscape.natural", elementType: "geometry", stylers: [{ color: "#bdebbf" }] },
  { featureType: "poi", elementType: "geometry", stylers: [{ color: "#a8e9b6" }] },
  { featureType: "poi.park", elementType: "geometry", stylers: [{ color: "#78dfa0" }] },
  { featureType: "road", elementType: "geometry", stylers: [{ color: "#f8fff2" }] },
  { featureType: "road", elementType: "geometry.stroke", stylers: [{ color: "#b5dfbf" }] },
  { featureType: "road.arterial", elementType: "geometry", stylers: [{ color: "#fff8a8" }] },
  { featureType: "road.highway", elementType: "geometry", stylers: [{ color: "#ffe57c" }] },
  { featureType: "transit", elementType: "geometry", stylers: [{ color: "#b8ddd1" }] },
  { featureType: "water", elementType: "geometry", stylers: [{ color: "#65d9df" }] },
  { featureType: "water", elementType: "labels.text.fill", stylers: [{ color: "#147f91" }] },
];
